### ISSUE TITLE
Allowing more than expected

### ISSUE THREAD

**Issue by tkawachi** [peterkhayes/rolling-rate-limiter#11]
Hi, I read [the blog](https://engineering.classdojo.com/blog/2015/02/06/rolling-rate-limiter/) about this library and I implemented my own program with the described method (redis sorted set). Then I found that it allows more requests than expected. I tracked down the problem and figured out the cause.

> Each user has a sorted set associated with them. The keys and values are identical, and equal to the (microsecond) times when actions were attempted.

In burst situation, more than one request may have a same timestamp. In this case, ZADD doesn't add an element to sorted set but updates the score to the same value. As a result, the request is not counted.

http://redis.io/commands/zadd

> If a specified member is already a member of the sorted set, the score is updated and the element reinserted at the right position to ensure the correct ordering.

My workaround is to use a random string as a value instead of timestamp.

I suppose this implementation might have the same issue. Hope this helps.

**Comment by peterkhayes** [comment]
Interesting!  I've used microseconds for the timestamp, and given our use case (rate limiting API requests behind a load balancer) it seems unlikely that we'll get multiple requests from a single user in a single microsecond except in some sort of DDOS situation, which will take us down anyway.

However, I think the random value is a good idea!  Maybe, instead of _replacing_ the timestamps with random strings, we could _append_ random strings to the stamps?  Storing the timestamps as values are useful to display the time left until the next request to the user, but we could always strip off the randomized bit before returning.  I'd be happy to accept a PR.

**Comment by peterkhayes** [comment]
It seems like this was fixed at some point several years ago by storing UUIDs as the values. Closing this issue now.
